//////////////////////////////LOCALHOST USER////////////////////////////////


###create new category
POST http://localhost:8080/categories HTTP/1.1
Content-Type: application/json

{
    "name": "Html"
   
}

###GET all category
GET http://localhost:8080/categories HTTP/1.1


###user1
POST http://localhost:8080/users HTTP/1.1
Content-Type: application/json

{
    "firstName": "Elizabeth", 
    "lastName": "Tellez", 
    "email": "eli@test.com", 
    "birthday": "10/20/1990",
    "password": "admin",
    "phone": "351876",
    "address": "205 N 500 W"
}

###user2
POST http://localhost:8080/users HTTP/1.1
Content-Type: application/json

{
    "firstName": "Owas", 
    "lastName": "Ogunniyi", 
    "email": "owas@test.com", 
    "birthday": "10/20/1990",
    "password": "admin",
    "phone": "351876",
    "address": "205 N 500 W"
}

###user3
POST http://localhost:8080/users HTTP/1.1
Content-Type: application/json

{
    "firstName": "Ariel", 
    "lastName": "Perez", 
    "email": "test3@test.com", 
    "birthday": "10/20/1990",
    "password": "admin",
    "phone": "351876",
    "address": "205 N 500 W"
}

###user4
POST http://localhost:8080/users HTTP/1.1
Content-Type: application/json

{
    "firstName": "Alexis", 
    "lastName": "Ortiz", 
    "email": "alexis@test.com", 
    "birthday": "10/20/1990",
    "password": "admin",
    "phone": "351876",
    "address": "205 N 500 W"
}

###GET all Users
GET http://localhost:8080/users HTTP/1.1


###User1 make a post
POST http://localhost:8080/post HTTP/1.1
Content-Type: application/json

{
    "title": "can you assign 2 classes to a single html element",
    "content": "I want to style html elements in CSS using class, not id. and I need to assign 2 classes to 1 element. I want one mother class e.g.'animal' and smaller classes e.g. 'mammal' & 'reptile'. I could just style every element in the smaller classes individually with id's but I'm working on a big project and that would take forever. is there a way to assign two classes to 1 element?", 
    "status": "Active",
    "categories": {
        "_id": "640a98999d611836b18002ff"
    },
    "users": {
        "_id": "640a998f9d611836b1800301",
        "firstName": "Elizabeth"
    }
}

###GET all Posts
GET http://localhost:8080/post HTTP/1.1

###User2 make a comment
POST http://localhost:8080/comments HTTP/1.1
Content-Type: application/json

{
    "comment": "Yes, you can easily give multiple classes to a single element, just separate them by a space. For example: <div class=animal mammal reptile>...</div> Now the above div has 3 classes, animal, mammal and reptile. And now you can target each just like you'd target a single class. ",    
    "posts": {
        "_id": "640a9c9f9d611836b180030f"
    },
    "users": {
        "_id": "640a99919d611836b1800303",
        "firstName": "Owas"
    }
}

###User3 make a comment to the user1 post
POST http://localhost:8080/comments HTTP/1.1
Content-Type: application/json

{
    "comment": "Yes, just simply add a space after the first class and add another.",    
    "posts": {
        "_id": "640a9c9f9d611836b180030f"
    },
    "users": {
        "_id": "640a99939d611836b1800305",
        "firstName": "Ariel"
    }
}

###User4 make a correction on the comment from user3
POST http://localhost:8080/comments HTTP/1.1
Content-Type: application/json

{
    "comment": "Yes, just simply add a space after the first class and add another.",    
    "posts": {
        "_id": "640a9c9f9d611836b180030f"
    },
    "users": {
        "_id": "640a9df89d611836b1800316",
        "firstName": "Alexis"
    }
}

###GET all Comments
GET http://localhost:8080/comments HTTP/1.1


