
////////////////////////////// RENDER.COM ////////////////////////////////


////////////////////////////// Category ////////////////////////////////

### PUT New Category

GET https://byui-cse-341-groupjasnah.onrender.com/categories HTTP/1.1

Content-Type: application/json

{

    "name":"Html"

}

### GET All Categories

GET https://byui-cse-341-groupjasnah.onrender.com/categories HTTP/1.1


////////////////////////////// User ////////////////////////////////


### PUT Login User

GET https://byui-cse-341-groupjasnah.onrender.com/auth/login HTTP/1.1

Content-Type: application/json

{

  "username": "Eliza",

  "password": "12345"

}


### GET Single User

GET https://byui-cse-341-groupjasnah.onrender.com/users/641605d88f4fd40ca9302c35 HTTP/1.1


### DELETE User

DELETE https://byui-cse-341-groupjasnah.onrender.com/users/641604b97619830c56ddaae6 HTTP/1.1

Content-Type: application/json

{

  "userId": "641604b97619830c56ddaae6",

  "username": "Eliza"

}


### POST User
POST https://byui-cse-341-groupjasnah.onrender.com/auth/register HTTP/1.1

Content-Type: application/json

{

  "username": "Owamamwen",

  "email": "owas@gmail.com",


  "password": "12345"
}

### PUT User
PUT  https://byui-cse-341-groupjasnah.onrender.com/users/64160ceed5e70b0e43ea30d6 HTTP/1.1

Content-Type: application/json

{

  "userId": "64160ceed5e70b0e43ea30d6",

  "username": "Eliza",

  "password": "12345",

  "firstName": "Elizabeth",

  "lastName": "Tellez",

  "email": "owas@cse341.com"

}


////////////////////////////// POST NEW Content ////////////////////////////////


### POST User Make A New Blog Post
POST https://byui-cse-341-groupjasnah.onrender.com/posts HTTP/1.1

Content-Type: application/json

{
  "username": "Eliza",

  "title": "Html",

  "desc": "The HyperText Markup Language or HTML is the standard markup language for documents designed to be displayed in a web browser. It is often assisted by technologies such as Cascading Style Sheets (CSS) and scripting languages such as JavaScript."

}

### PUT update the Blog Post
POST https://byui-cse-341-groupjasnah.onrender.com/posts/64161092fa9f8b0eba01d82e HTTP/1.1

Content-Type: application/json

{
  "username": "Eliza",

  "title": "Html",

  "desc": "HTML is the standard markup language for documents designed to be displayed in a web browser."

}

### GET single Blog Post
POST https://byui-cse-341-groupjasnah.onrender.com/posts/64161092fa9f8b0eba01d82e HTTP/1.1


### GET All Blog Post
POST https://byui-cse-341-groupjasnah.onrender.com/posts HTTP/1.1

### GET All Blog Post by username
POST https://byui-cse-341-groupjasnah.onrender.com/posts?user=Eliza HTTP/1.1

### PUT update the Blog Post
POST https://byui-cse-341-groupjasnah.onrender.com/posts/64161092fa9f8b0eba01d82e HTTP/1.1

Content-Type: application/json

{

  "username": "Eliza"
  
}